### ISSUE TITLE
ORM links problem

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/aiida-crystal-dft#21]
Happened while:
```
...
('Li', 'F')
Got 17 hits
Submitted WorkChain 519 for LiF/225/cF8
root@aiida-new:~/mpds-aiida# verdi process report 519
2020-02-11 19:50:20 [217 | WARNING]: Skipping phonon frequency calculation
2020-02-11 19:50:20 [218 |  REPORT]: [519|MPDSCrystalWorkchain|on_except]: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/plumpy/process_states.py", line 220, in execute
    result = self.run_fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/aiida/engine/processes/workchains/workchain.py", line 181, in _do_step
    finished, stepper_result = self._stepper.step()
  File "/usr/local/lib/python3.7/dist-packages/plumpy/workchains.py", line 283, in step
    finished, result = self._child_stepper.step()
  File "/usr/local/lib/python3.7/dist-packages/plumpy/workchains.py", line 234, in step
    return True, self._fn(self._workchain)
  File "/usr/local/lib/python3.7/dist-packages/mpds_aiida/workflows/crystal.py", line 164, in calculate_elastic_constants
    self.ctx.inputs.crystal.structure = self.ctx.optimise.outputs.output_structure
  File "/usr/local/lib/python3.7/dist-packages/aiida/orm/utils/managers.py", line 85, in __getattr__
    return self._get_node_by_link_label(label=name)
  File "/usr/local/lib/python3.7/dist-packages/aiida/orm/utils/managers.py", line 66, in _get_node_by_link_label
    return self._node.get_outgoing(link_type=self._link_type).get_node_by_label(label)
  File "/usr/local/lib/python3.7/dist-packages/aiida/orm/utils/links.py", line 308, in get_node_by_label
    raise exceptions.NotExistent('no neighbor with the label {} found'.format(label))
aiida.common.exceptions.NotExistent: no neighbor with the label output_structure found
```

**Comment by blokhin** [comment]
This is a too generic error, can be caused by multiple reasons, closing.
