### ISSUE TITLE
Predefined families should appear in **listfamilies**

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/aiida-crystal-dft#25]
```
root@aiida-repl:~# verdi data crystal createpredefined
Created 5 predefined basis families:
STO-3G, STO-6G, POB-DZVP, POB-DZVPP, POB-TZVP
root@aiida-repl:~# verdi data crystal listfamilies
Family       Num Basis Sets
---------  ----------------
TZVP_REV2                47

root@aiida-repl:~#
```

**Comment by ansobolev** [comment]
The problem here is that `listfamilies` can be filtered by element, and predefined basis families also are defined for a subset of elements, so they also should be filtered somehow

**Comment by blokhin** [comment]
Do you mean, we must know in advance, which elements exactly are supported?

**Comment by blokhin** [comment]
@ansobolev or anything else?

**Comment by blokhin** [comment]
Now broken:
```
root@aiida-cloud-rev-3:~# verdi data crystal_dft listfamilies
/usr/local/lib/python3.7/dist-packages/aiida/orm/groups.py:42: UserWarning: could not load entry point `crystal_dft.basis_family`, falling back onto `Group` base class.
  warnings.warn(message)  # pylint: disable=no-member
Traceback (most recent call last):
  File "/usr/local/bin/verdi", line 10, in <module>
    sys.exit(verdi())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/cli/basis.py", line 64, in listfamilies
    bases, groups = basis_family_cls.get_families(filter_elements=element)
  File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/data/basis_family.py", line 247, in get_families
    predefined_bases = [b for b in predefined_bases if
  File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/data/basis_family.py", line 249, in <listcomp>
    for n in BASIS_FAMILY_KWDS[b.name]})]
KeyError: 'TZVP_REV2'
```
