### ISSUE TITLE
verdi data crystal uploadfamily: AiidaDeprecationWarning and format error

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/aiida-crystal-dft#33]
This script downloads and saves the BS element-wise automatically:

`https://github.com/mpds-io/mpds-aiida/blob/master/bin/run_get_unito_bsl.py`

everything is nicely prepared:

```
root@aiida-test-cloud:~/MPDSBSL# ls
Ac.basis  As.basis  Ca.basis  Cl.basis  Dy.basis  Fe.basis  Hf.basis  Ir.basis  Mg.basis  Nb.basis  O.basis   Pm.basis  Rh.basis  Se.basis  Tb.basis  Tm.basis  Yb.basis
Ag.basis  B.basis   C.basis   Cm.basis  Er.basis  Ga.basis  Hg.basis  K.basis   Mn.basis  Nd.basis  Os.basis  Pr.basis  Ru.basis  Si.basis  Tc.basis  U.basis   Zn.basis
Al.basis  Be.basis  Cd.basis  Co.basis  Es.basis  Gd.basis  Ho.basis  La.basis  Mo.basis  Ne.basis  Pa.basis  Pu.basis  S.basis   Sm.basis  Te.basis  V.basis   Zr.basis
Am.basis  Bk.basis  Ce.basis  Cr.basis  Eu.basis  Ge.basis  I.basis   Li.basis  Na.basis  Ni.basis  P.basis   Rb.basis  Sb.basis  Sn.basis  Th.basis  W.basis
Ar.basis  Br.basis  Cf.basis  Cu.basis  F.basis   H.basis   In.basis  Lu.basis  N.basis   Np.basis  Pd.basis  Re.basis  Sc.basis  Sr.basis  Ti.basis  Y.basis
```

However, `verdi data crystal uploadfamily --name=MPDSBSL` does not like these basis set and thinks there are more than one basis set for some element, which is not true.

NB also `AiidaDeprecationWarning`

**Comment by blokhin** [comment]
OK, my bad, there was an error in `run_get_unito_bsl.py` script (now fixed).

**Comment by blokhin** [comment]
@ansobolev OTOH better error message would be very helpful. NB also `AiidaDeprecationWarning`

**Comment by blokhin** [comment]
FYI the full error message was:
```
$ verdi data crystal_dft uploadfamily --name=TEST
-/usr/local/lib/python3.7/dist-packages/aiida/orm/nodes/node.py:998: AiidaDeprecationWarning: the `use_cache` argument is deprecated and will be removed in `v2.0.0`
  'the `use_cache` argument is deprecated and will be removed in `v2.0.0`', AiidaDeprecationWarning
Traceback (most recent call last):
  File "/usr/local/bin/verdi", line 10, in <module>
    sys.exit(verdi())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/cli/basis.py", line 29, in uploadfamily
    description=description
  File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/data/basis_family.py", line 217, in upload
    added = group.add(bases)
  File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/data/basis_family.py", line 81, in add
    format(self.name))
ValueError: Trying to add more than one basis set for some element to basis family TEST
```
