### ISSUE TITLE
KeyError in add_valence_electrons

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/aiida-crystal-dft#38]
```
# verdi process report 30280
*** 30280 [HgEr/221/cP2: Geometry optimization [2]]: None
*** Scheduler output: N/A
*** Scheduler errors: N/A
*** 1 LOG MESSAGES:
+-> REPORT at 2020-04-21 15:49:14.726775+00:00
 | [30280|CrystalParallelCalculation|on_except]: Traceback (most recent call last):
 |   File "/usr/local/lib/python3.7/dist-packages/aiida/engine/processes/calcjobs/tasks.py", line 78, in do_upload
 |     calc_info, script_filename = process.presubmit(folder)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida/engine/processes/calcjobs/calcjob.py", line 312, in presubmit
 |     calc_info = self.prepare_for_submission(folder)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/calculations/parallel.py", line 24, in prepare_for_submission
 |     self._prepare_input_files(folder)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/calculations/common.py", line 112, in _prepare_input_files
 |     basis_dict['basis_family'], {})
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/io/d12_write.py", line 71, in write_input
 |     outstr = _basis_set_block(outstr, indict, basis, atom_props, is_basis_family)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/io/d12_write.py", line 184, in _basis_set_block
 |     content = basis.content
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/data/basis_family.py", line 176, in content
 |     basis_strings = [b.content(state) for b, state in zip(bases, oxi_states)]
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/data/basis_family.py", line 176, in <listcomp>
 |     basis_strings = [b.content(state) for b, state in zip(bases, oxi_states)]
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/data/basis.py", line 48, in content
 |     basis = self.set_oxistate(oxi_state, high_spin_preferred)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/data/basis.py", line 110, in set_oxistate
 |     occs = add_valence_electrons(-oxi_state, occs, self.element, high_spin_preferred)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/data/basis.py", line 199, in add_valence_electrons
 |     n_e = occs[orb][i_valence[orb]]
 | KeyError: 'p'
```

**Comment by blokhin** [comment]
Also **IndexError** in **guess_oxistates**:
```
# verdi process report 30400
*** 30400 [MgTb/221/cP2: Geometry optimization [2]]: None
*** Scheduler output: N/A
*** Scheduler errors: N/A
*** 1 LOG MESSAGES:
+-> REPORT at 2020-04-21 15:49:27.807108+00:00
 | [30400|CrystalParallelCalculation|on_except]: Traceback (most recent call last):
 |   File "/usr/local/lib/python3.7/dist-packages/aiida/engine/processes/calcjobs/tasks.py", line 78, in do_upload
 |     calc_info, script_filename = process.presubmit(folder)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida/engine/processes/calcjobs/calcjob.py", line 312, in presubmit
 |     calc_info = self.prepare_for_submission(folder)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/calculations/parallel.py", line 24, in prepare_for_submission
 |     self._prepare_input_files(folder)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/calculations/common.py", line 109, in _prepare_input_files
 |     oxi_states = guess_oxistates(self.inputs.structure)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/utils/electrons.py", line 208, in guess_oxistates
 |     return dict(zip(elements, sorted(weights.items(), key=lambda x: x[1], reverse=True)[0][0]))
 | IndexError: list index out of range
```

**Comment by blokhin** [comment]
Only occurs with the *f-element* compounds

**Comment by ansobolev** [comment]
What are the bases used for f-elements? Where can I have a look on them?

**Comment by ansobolev** [comment]
Cannot reproduce. Can you give more data?

**Comment by ansobolev** [comment]
The problem for HgEr was in the basis for Hg. Hg is a 6s element with the known oxidation state of -2, so 2 electrons should be added to 6p orbital. However, in the [basis](https://www.crystal.unito.it/Basis_Sets/mercury.html#Hg_weihrich_2005) there is no empty bases for p orbitals. Added a somewhat more clear error message. The reason for the second error was the fact that no known negative oxidation states are known for both Mg and Tb, so no oxidation state combinations were returned. In this case also the error is clarified in the error message. However, as a side note, it seems that recombining electrons should work only in the case of ionic bonding in the compound, and it not going to work in the cases of metallic alloys, as are the systems in question.
