### ISSUE TITLE
guess_spinlock: NotImplementedError: Structure does not contain transition elements

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/aiida-crystal-dft#56]
Please could we do anything with that?
```
root@aiida-rev-6:~# verdi process report 324
*** 324 [MgH2Cl4/Imma (74): Geometry optimization [1]]: None
*** Scheduler output: N/A
*** Scheduler errors: N/A
*** 1 LOG MESSAGES:
+-> REPORT at 2021-02-12 01:13:29.359913+00:00
 | [324|CrystalParallelCalculation|on_except]: Traceback (most recent call last):
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/calculations/common.py", line 133, in _prepare_input_files
 |     spinlock = guess_spinlock(self.inputs.structure)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/utils/electrons.py", line 238, in guess_spinlock
 |     raise NotImplementedError("Structure does not contain transition elements")
 | NotImplementedError: Structure does not contain transition elements
 |
 | During handling of the above exception, another exception occurred:
 |
 | Traceback (most recent call last):
 |   File "/usr/local/lib/python3.7/dist-packages/aiida/engine/processes/calcjobs/tasks.py", line 79, in do_upload
 |     calc_info = process.presubmit(folder)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida/engine/processes/calcjobs/calcjob.py", line 445, in presubmit
 |     calc_info = self.prepare_for_submission(folder)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/calculations/parallel.py", line 26, in prepare_for_submission
 |     self._prepare_input_files(folder)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/calculations/common.py", line 148, in _prepare_input_files
 |     format(err))
 | aiida.common.exceptions.InputValidationError: an input file could not be created from the parameters: Structure does not contain transition elements
 |
 | The above exception was the direct cause of the following exception:
 |
 | Traceback (most recent call last):
 |   File "/usr/local/lib/python3.7/dist-packages/plumpy/processes.py", line 1085, in step
 |     next_state = yield self._run_task(self._state.execute)
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 4, in raise_exc_info
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1063, in run
 |     yielded = self.gen.throw(*exc_info)
 |   File "/usr/local/lib/python3.7/dist-packages/plumpy/processes.py", line 507, in _run_task
 |     tornado.stack_context.StackContext(self._process_scope), functools.partial(coro, *args, **kwargs)
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 4, in raise_exc_info
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1063, in run
 |     yielded = self.gen.throw(*exc_info)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida/engine/processes/calcjobs/tasks.py", line 353, in execute
 |     yield self._launch_task(task_upload_job, self.process, transport_queue)
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 4, in raise_exc_info
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1063, in run
 |     yielded = self.gen.throw(*exc_info)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida/engine/processes/calcjobs/tasks.py", line 406, in _launch_task
 |     result = yield self._task
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 4, in raise_exc_info
 |   File "/usr/local/lib/python3.7/dist-packages/aiida/engine/utils.py", line 115, in execute_coroutine
 |     result = yield coro(future)
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 4, in raise_exc_info
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1063, in run
 |     yielded = self.gen.throw(*exc_info)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida/engine/processes/calcjobs/tasks.py", line 91, in task_upload_job
 |     do_upload, initial_interval, max_attempts, logger=node.logger, ignore_exceptions=ignore_exceptions
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 4, in raise_exc_info
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1063, in run
 |     yielded = self.gen.throw(*exc_info)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida/engine/utils.py", line 174, in exponential_backoff_retry
 |     result = yield coro()
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 4, in raise_exc_info
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1069, in run
 |     yielded = self.gen.send(value)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida/engine/processes/calcjobs/tasks.py", line 81, in do_upload
 |     raise PreSubmitException('exception occurred in presubmit call') from exception
 | aiida.engine.processes.calcjobs.tasks.PreSubmitException: exception occurred in presubmit call
```

**Comment by ansobolev** [comment]
We can turn off `guess_spinlock` for non-transition elements; make it another yml file, for instance
