### ISSUE TITLE
AiiDA apparently confuses *p*- and *sp*-orbitals in our basis set implementation

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/aiida-crystal-dft#57]
```
root@aiida-rev-6:~# verdi process report 1478
*** 1478 [Li2Pt/191/hP3: Geometry optimization [1]]: None
*** Scheduler output: N/A
*** Scheduler errors: N/A
*** 1 LOG MESSAGES:
+-> REPORT at 2021-02-13 01:03:03.963000+00:00
 | [1478|CrystalParallelCalculation|on_except]: Traceback (most recent call last):
 |   File "/usr/local/lib/python3.7/dist-packages/aiida/engine/processes/calcjobs/tasks.py", line 79, in do_upload
 |     calc_info = process.presubmit(folder)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida/engine/processes/calcjobs/calcjob.py", line 445, in presubmit
 |     calc_info = self.prepare_for_submission(folder)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/calculations/parallel.py", line 26, in prepare_for_submission
 |     self._prepare_input_files(folder)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/calculations/common.py", line 145, in _prepare_input_files
 |     d12_file = D12(parameters=self.inputs.parameters.get_dict(), basis=basis_dict['basis_family'])
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/io/d12.py", line 19, in __init__
 |     self.use_basis(basis)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/io/d12.py", line 49, in use_basis
 |     self._basis = basis.content
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/data/basis_family.py", line 180, in content
 |     basis_strings = [b.content(state) for b, state in zip(bases, oxi_states)]
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/data/basis_family.py", line 180, in <listcomp>
 |     basis_strings = [b.content(state) for b, state in zip(bases, oxi_states)]
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/data/basis.py", line 48, in content
 |     basis = self.set_oxistate(oxi_state, high_spin_preferred)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/data/basis.py", line 105, in set_oxistate
 |     occs = self._get_occupations()
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/data/basis.py", line 132, in _get_occupations
 |     return get_occupations(self.get_dict())
 |   File "/usr/local/lib/python3.7/dist-packages/aiida_crystal_dft/data/basis.py", line 146, in get_occupations
 |     result[orbital_data[orb]["l"]].append(e)
 | KeyError: 'p'
 |
 | The above exception was the direct cause of the following exception:
 |
 | Traceback (most recent call last):
 |   File "/usr/local/lib/python3.7/dist-packages/plumpy/processes.py", line 1085, in step
 |     next_state = yield self._run_task(self._state.execute)
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 4, in raise_exc_info
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1063, in run
 |     yielded = self.gen.throw(*exc_info)
 |   File "/usr/local/lib/python3.7/dist-packages/plumpy/processes.py", line 507, in _run_task
 |     tornado.stack_context.StackContext(self._process_scope), functools.partial(coro, *args, **kwargs)
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 4, in raise_exc_info
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1063, in run
 |     yielded = self.gen.throw(*exc_info)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida/engine/processes/calcjobs/tasks.py", line 353, in execute
 |     yield self._launch_task(task_upload_job, self.process, transport_queue)
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 4, in raise_exc_info
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1063, in run
 |     yielded = self.gen.throw(*exc_info)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida/engine/processes/calcjobs/tasks.py", line 406, in _launch_task
 |     result = yield self._task
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 4, in raise_exc_info
 |   File "/usr/local/lib/python3.7/dist-packages/aiida/engine/utils.py", line 115, in execute_coroutine
 |     result = yield coro(future)
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 4, in raise_exc_info
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1063, in run
 |     yielded = self.gen.throw(*exc_info)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida/engine/processes/calcjobs/tasks.py", line 91, in task_upload_job
 |     do_upload, initial_interval, max_attempts, logger=node.logger, ignore_exceptions=ignore_exceptions
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 4, in raise_exc_info
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1063, in run
 |     yielded = self.gen.throw(*exc_info)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida/engine/utils.py", line 174, in exponential_backoff_retry
 |     result = yield coro()
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1055, in run
 |     value = future.result()
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/concurrent.py", line 238, in result
 |     raise_exc_info(self._exc_info)
 |   File "<string>", line 4, in raise_exc_info
 |   File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 1069, in run
 |     yielded = self.gen.send(value)
 |   File "/usr/local/lib/python3.7/dist-packages/aiida/engine/processes/calcjobs/tasks.py", line 81, in do_upload
 |     raise PreSubmitException('exception occurred in presubmit call') from exception
 | aiida.engine.processes.calcjobs.tasks.PreSubmitException: exception occurred in presubmit call
```

**Comment by blokhin** [comment]
@akvatol please, let's investigate it for `Li2Pt/191`
