### ISSUE TITLE
Non-informative errors if yascheduler fails

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/aiida-crystal-dft#63]
The reason of below is that `yasubmit` scripts fails, but there is no clue for that in the traceback...
```
...
[172|MPDSStructureWorkChain|on_except]: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aiida/orm/utils/managers.py", line 91, in _get_node_by_link_label
    node = attribute_dict[label]
KeyError: 'output_structure'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aiida/orm/utils/managers.py", line 139, in __getattr__
    return self._get_node_by_link_label(label=name)
  File "/usr/local/lib/python3.9/dist-packages/aiida/orm/utils/managers.py", line 118, in _get_node_by_link_label
    raise NotExistent from exception
aiida.common.exceptions.NotExistent

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/plumpy/process_states.py", line 228, in execute
    result = self.run_fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/aiida/engine/processes/workchains/workchain.py", line 252, in _do_step
    finished, stepper_result = self._stepper.step()
  File "/usr/local/lib/python3.9/dist-packages/plumpy/workchains.py", line 295, in step
    finished, result = self._child_stepper.step()
  File "/usr/local/lib/python3.9/dist-packages/plumpy/workchains.py", line 528, in step
    finished, result = self._child_stepper.step()
  File "/usr/local/lib/python3.9/dist-packages/plumpy/workchains.py", line 295, in step
    finished, result = self._child_stepper.step()
  File "/usr/local/lib/python3.9/dist-packages/plumpy/workchains.py", line 428, in step
    finished, retval = self._child_stepper.step()
  File "/usr/local/lib/python3.9/dist-packages/plumpy/workchains.py", line 295, in step
    finished, result = self._child_stepper.step()
  File "/usr/local/lib/python3.9/dist-packages/plumpy/workchains.py", line 246, in step
    return True, self._fn(self._workchain)
  File "/usr/local/lib/python3.9/dist-packages/mpds_aiida/workflows/crystal.py", line 279, in check_and_get_results
    self.ctx.optimized_structure = calc.outputs.output_structure
  File "/usr/local/lib/python3.9/dist-packages/aiida/orm/utils/managers.py", line 145, in __getattr__
    raise NotExistentAttributeError(
aiida.common.exceptions.NotExistentAttributeError: Node<178> does not have an output with link label 'output_structure'
```

**Comment by ansobolev** [comment]
What is the output of ‘yasubmit‘ when it fails?

**Comment by blokhin** [comment]
@ansobolev unfortunately it’s not available to me, since it’s called by AiiDA (not sure, if it’s logged anywhere)

**Comment by ansobolev** [comment]
We can parse `yasubmit` output and see if it fails. But to do that we have to know what is the output of a failed script.

**Comment by blokhin** [comment]
@ansobolev do you have any ideas on that?

**Comment by ansobolev** [comment]
The problem is that if you run `yasubmit` manually, it works normally
