### ISSUE TITLE
Failing *recursive_update* due to the details in the schema

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/aiida-crystal-dft#66]
If I add `BROYDEN` to `on_error` like this:

```
    on_error:
      300:
        crystal:
          geometry:
            optimise:
              hessian: HESSIDEN
              convergence:
                TOLDEE: 9
                MAXCYCLE: 150
          scf:
            numerical:
              TOLINTEG: [8, 8, 8, 8, 40]
            fock_mixing:
              BROYDEN: [0.0001, 95, 5]
```
the `recursive_update` function fails:
```
2022-12-18 01:57:04 [1657 | REPORT]: [6522|MPDSStructureWorkChain|on_except]: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/plumpy/process_states.py", line 228, in execute
    result = self.run_fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/aiida/engine/processes/workchains/workchain.py", line 235, in run
    return self._do_step()
  File "/usr/local/lib/python3.9/dist-packages/aiida/engine/processes/workchains/workchain.py", line 252, in _do_step
    finished, stepper_result = self._stepper.step()
  File "/usr/local/lib/python3.9/dist-packages/plumpy/workchains.py", line 295, in step
    finished, result = self._child_stepper.step()
  File "/usr/local/lib/python3.9/dist-packages/plumpy/workchains.py", line 246, in step
    return True, self._fn(self._workchain)
  File "/usr/local/lib/python3.9/dist-packages/mpds_aiida/workflows/crystal.py", line 162, in init_inputs
    recursive_update(c_err_input, err_input)
  File "/usr/local/lib/python3.9/dist-packages/aiida_crystal_dft/utils/__init__.py", line 59, in recursive_update
    d[k] = recursive_update(d.get(k, {}), v)
  File "/usr/local/lib/python3.9/dist-packages/aiida_crystal_dft/utils/__init__.py", line 59, in recursive_update
    d[k] = recursive_update(d.get(k, {}), v)
  File "/usr/local/lib/python3.9/dist-packages/aiida_crystal_dft/utils/__init__.py", line 59, in recursive_update
    d[k] = recursive_update(d.get(k, {}), v)
  File "/usr/local/lib/python3.9/dist-packages/aiida_crystal_dft/utils/__init__.py", line 61, in recursive_update
    d[k] = v
TypeError: 'str' object does not support item assignment
```

**Comment by ansobolev** [comment]
You want to add `BROYDEN` to whatever it is in `fock_mixing`, right?

**Comment by blokhin** [comment]
@ansobolev yes, exactly
