### ISSUE TITLE
AiiDA's UNKNOWN_ERROR

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/aiida-crystal-dft#67]
```
$ verdi process report 6953

2022-12-18 05:34:14 [1794 | REPORT]: [6953|BaseCrystalWorkChain|init_inputs]: CrH/194: Phonon frequencies: is_magnetic is set, guessing magnetism
2022-12-18 05:34:37 [1797 | REPORT]: [6953|BaseCrystalWorkChain|retrieve_results]: The calculations failed with exit message: Unknown error
2022-12-18 05:34:37 [1798 | REPORT]: [6953|BaseCrystalWorkChain|on_except]: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aiida/common/extendeddicts.py", line 51, in __getattr__
    return self[attr]
KeyError: 'UNKNOWN_ERROR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/plumpy/process_states.py", line 228, in execute
    result = self.run_fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/aiida/engine/processes/workchains/workchain.py", line 252, in _do_step
    finished, stepper_result = self._stepper.step()
  File "/usr/local/lib/python3.9/dist-packages/plumpy/workchains.py", line 295, in step
    finished, result = self._child_stepper.step()
  File "/usr/local/lib/python3.9/dist-packages/plumpy/workchains.py", line 246, in step
    return True, self._fn(self._workchain)
  File "/usr/local/lib/python3.9/dist-packages/aiida_crystal_dft/workflows/base.py", line 173, in retrieve_results
    return self.exit_codes.UNKNOWN_ERROR
  File "/usr/local/lib/python3.9/dist-packages/aiida/common/extendeddicts.py", line 54, in __getattr__
    raise AttributeError(errmsg)
AttributeError: 'ExitCodesNamespace' object has no attribute 'UNKNOWN_ERROR'
```

**Comment by blokhin** [comment]
@ansobolev do you have any idea? :flushed:

**Comment by blokhin** [comment]
Ah, I see, we just don't handle it here: https://github.com/tilde-lab/aiida-crystal-dft/blob/48479480b6e5de4df4127f62d9f07233260ba161/aiida_crystal_dft/calculations/common.py#L64-L83

**Comment by blokhin** [comment]
e.g. for Rb19O3/226

```
2026-05-06 14:30:47 [20934 | WARNING]: could not parse scheduler output: the `_scheduler-stdout.txt` file is missing
2026-05-06 14:30:47 [20935 | WARNING]: output parser returned exit code<400>: Unknown error
...
2026-05-06 14:30:47 [20936 | REPORT]: [42843|BaseCrystalWorkChain|retrieve_results]: The calculations failed with exit message: Unknown error
2026-05-06 14:30:47 [20937 | REPORT]: [42843|BaseCrystalWorkChain|on_except]: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/aiida/common/extendeddicts.py", line 55, in __getattr__
    return self[attr]
           ~~~~^^^^^^
KeyError: 'UNKNOWN_ERROR'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/plumpy/process_states.py", line 250, in execute
    result = await self.run_fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/plumpy/utils.py", line 211, in wrap
    return await run_with_portal(coro_or_fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/plumpy/greenback_bridge.py", line 37, in run_with_portal
    return await greenback.with_portal_run_sync(fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/greenback/_impl.py", line 567, in with_portal_run_sync
    res: T = await _greenback_shim_sync(partial(sync_fn, *args, **kwds))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/greenback/_impl.py", line 290, in _greenback_shim_sync
    request = resume_greenlet.switch()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiida/engine/processes/workchains/workchain.py", line 320, in _do_step
    finished, stepper_result = self._stepper.step()
                               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/plumpy/workchains.py", line 305, in step
    finished, result = self._child_stepper.step()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/plumpy/workchains.py", line 258, in step
    return True, self._fn(self._workchain)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiida_crystal_dft/workflows/base.py", line 173, in retrieve_results
    return self.exit_codes.UNKNOWN_ERROR
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiida/common/extendeddicts.py", line 58, in __getattr__
    raise AttributeError(errmsg)
AttributeError: 'ExitCodesNamespace' object has no attribute 'UNKNOWN_ERROR'
```
