### ISSUE TITLE
Problems on AiiDA v2.5.1

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/aiida-crystal-dft#68]
```
$ verdi process report 129
2024-05-23 14:46:56 [10 | REPORT]: [129|MPDSStructureWorkChain|init_inputs]: Guessed nonmetallic bonding; using nonmetallic.yml as modeling template
2024-05-23 14:46:56 [11 | REPORT]: [129|MPDSStructureWorkChain|_run_calc_crystal]: optimise: Using structure from input
2024-05-23 14:46:58 [12 | REPORT]:   [135|BaseCrystalWorkChain|init_inputs]: MgO/225: Geometry optimization: is_magnetic is set, guessing magnetism
2024-05-23 14:47:04 [14 | REPORT]: [129|MPDSStructureWorkChain|on_except]: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/aiida/orm/utils/managers.py", line 87, in _get_node_by_link_label
    node = attribute_dict[label]
           ~~~~~~~~~~~~~~^^^^^^^
KeyError: 'output_structure'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/aiida/orm/utils/managers.py", line 132, in __getattr__
    return self._get_node_by_link_label(label=name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiida/orm/utils/managers.py", line 115, in _get_node_by_link_label
    raise NotExistent from exception
aiida.common.exceptions.NotExistent

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/plumpy/process_states.py", line 228, in execute
    result = self.run_fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiida/engine/processes/workchains/workchain.py", line 313, in _do_step
    finished, stepper_result = self._stepper.step()
                               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/plumpy/workchains.py", line 295, in step
    finished, result = self._child_stepper.step()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/plumpy/workchains.py", line 538, in step
    finished, result = self._child_stepper.step()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/plumpy/workchains.py", line 295, in step
    finished, result = self._child_stepper.step()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/plumpy/workchains.py", line 438, in step
    finished, retval = self._child_stepper.step()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/plumpy/workchains.py", line 295, in step
    finished, result = self._child_stepper.step()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/plumpy/workchains.py", line 246, in step
    return True, self._fn(self._workchain)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/mpds_aiida/workflows/crystal.py", line 283, in check_and_get_results
    self.ctx.optimized_structure = calc.outputs.output_structure
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiida/orm/utils/managers.py", line 138, in __getattr__
    raise NotExistentAttributeError(
aiida.common.exceptions.NotExistentAttributeError: Node<135> does not have an output with link label 'output_structure'
```

In addition, there are also problems with `verdi data crystal_dft uploadfamily --name=XXX` and `verdi data crystal_dft listfamilies` as `XXX` does not show up after upload.

**Comment by blokhin** [comment]
Solution: as seen from a connected graph node, `spglib==2.4.0` is not compatible (cf. https://github.com/basf/metis-backend/pull/23), downgrade to `2.0.2`

**Comment by akvatol** [comment]
@blokhin 
The problem occurs in the `CrystalParallelCalculation` workflow:
```python
 |   File "/root/envs/aiida/lib/python3.11/site-packages/aiida/engine/processes/calcjobs/tasks.py", line 91, in do_upload
 |     calc_info = process.presubmit(folder)
 |                 ^^^^^^^^^^^^^^^^^^^^^^^^^
 |   File "/root/envs/aiida/lib/python3.11/site-packages/aiida/engine/processes/calcjobs/calcjob.py", line 866, in presubmit
 |     calc_info = self.prepare_for_submission(folder)
 |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 |   File "/root/envs/aiida/lib/python3.11/site-packages/aiida_crystal_dft/calculations/parallel.py", line 26, in prepare_for_submission
 |     self._prepare_input_files(folder)
 |   File "/root/envs/aiida/lib/python3.11/site-packages/aiida_crystal_dft/calculations/common.py", line 137, in _prepare_input_files
 |     spinlock = guess_spinlock(self.inputs.structure)
 |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 |   File "/root/envs/aiida/lib/python3.11/site-packages/aiida_crystal_dft/utils/electrons.py", line 229, in guess_spinlock
 |     composition = to_primitive(structure).get_composition()
 |                   ^^^^^^^^^^^^^^^^^^^^^^^
 |   File "/root/envs/aiida/lib/python3.11/site-packages/aiida_crystal_dft/utils/geometry.py", line 140, in to_primitive
 |     cell, positions, numbers = spglib.find_primitive(structure.get_ase())
 |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 |   File "/root/envs/aiida/lib/python3.11/site-packages/spglib/spglib.py", line 1450, in find_primitive
 |     lattice, positions, numbers, _ = _expand_cell(cell)
 |                                      ^^^^^^^^^^^^^^^^^^
 |   File "/root/envs/aiida/lib/python3.11/site-packages/spglib/spglib.py", line 2054, in _expand_cell
 |     lattice = np.array(np.transpose(cell[0]), dtype="double", order="C")
 |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 | TypeError: float() argument must be a string or a real number, not 'Atom'
```
`SPGlib` no longer supports `ase.Atoms` since version 2.3.0 (ASE Atoms-style input was dropped by @lan496 in https://github.com/spglib/spglib/pull/386).

Going to fix this by making simple `ase_to_spg` function.
